### ISSUE TITLE
js-localization/localization.js missing

### ISSUE THREAD

**Issue by adriaanvw** [LearningLocker/learninglocker#451]
Hi,

I've just done a clean install of LearningLocker on Ubuntu 14.04, which seems to be running OK. However I did notice several of the following type of entries in the /var/www/learninglocker/error.log file:

2014/11/24 14:06:38 [error] 1021#0: *10 open() "/var/www/learninglocker/public/js-localization/localization.js" failed (2: No such file or directory), client: 81.111.11.11, server: learninglocker.mydomain.com, request: "GET /js-localization/localization.js HTTP/1.1", host: "learninglocker.mydomain.com", referrer: "http://learninglocker.mydomain.com/lrs/5473380cc556dc21048b456a/endpoint"

I searched around for the file and eventually found it here:
/var/www/learninglocker/vendor/andywer/js-localization/public/js/localization.js

I made a copy to:
/var/www/learninglocker/public/js-localization/localization.js

Since then the errors have stopped. I don't know of what significance this type or error is, or to what extent it will affect Learning Locker's behavior, but thought it might be worth reporting for correction in future releases.

Thanks,
Adriaan

Version: 1.1.2 (although the VERSION file says 1.1.0)
Steps to reproduce the bug: Log on to the admin console, browse settings, etc.
Expected behaviour potentially referencing the xAPI specification: No errors.
Actual behaviour potentially with a screenshot.: Errors
Database and authentication: Mongo with basic authentication.

**Comment by ryansmith94** [comment]
I think this should be fixed on the issue/conformance branch. So I'll close this for now.

**Comment by philsown** [comment]
We're attempting to install this using release 1.3.4 and still encountering this problem. Looks like the issue/conformance branch is gone. Was that fix rolled into 1.3.4?

We did a new install, ran composer install & the bower install in public/js. What are we missing?

**Comment by ryansmith94** [comment]
Hi @philsown, thanks for your comment. Sorry to hear that you're still getting this issue. It looks like this was actually rolled into 1.2.2.

Please could you take a look at the ["'Reporting' page is empty" thread](https://groups.google.com/forum/#!searchin/learning-locker/localization.js/learning-locker/PvaP4wgbQNY/QeceJckgF6oJ) on the Google Group and let me know if anything there helps you?

**Comment by jamarr81** [comment]
This still happens in 1.12.1. I followed the instructions [here](http://cloudboffins.com/advanced-projects/learning-locker-lrs-free-server-part-5/) and manually copied the localization.js file from the vendor's directory into the public/js-localization directory. It seems like this 'asset' is not being properly managed.
