### ISSUE TITLE
Admin dashboard takes 15 seconds to load

### ISSUE THREAD

**Issue by salexfo** [LearningLocker/learninglocker#771]
Version
1.11.0

If you have more than 200,000 statements if will takes you quite considerable time to load your admin dashboard after login.

I tried to remove the functions public function getStats and public function getGraphData and still the load time was more than 10 seconds. I believe it might be something to do with the rendering of the graph and/or the way assests are loaded (JS before CSS). I have added an index on statement.timestamp but it did little do improve the situation.

See attached.
![selection_564](https://cloud.githubusercontent.com/assets/8767588/12325496/560b2fae-bad3-11e5-823c-559d12cedee5.png)

Thanks,
Alexander

**Comment by ht2** [comment]
Which branch are you running at the moment? We've being trying to address a lot of these issues in the development and issue branches we have at the moment? The issues are related to preloading the (slow) graph data into the body of the HTML page, which has been changed in the develop branch I believe.

I would certainly suggest at least deploying from develop if possible, `issue/storedDate` also looks to address indexing on the stored value, which was attempting to sort on a string value, so that would also be a good one to try out. Note that these branches typically require migrations, so your data will be changed to allow it to work in the new branch, and you would need to reverse (rollback) the migrations before going back to your original branch. Ideally, duplicate your database and give it a try on one of the new branches.

**Comment by salexfo** [comment]
@ht2 Production. Version 1.11.0

**Comment by ht2** [comment]
OK then the above applies; we have a release planned that will substantially cut time off many of these areas, but there are still some outstanding issues to be resolved before we can push as a master release (most noticeable #772 at the moment). As always, contributions from the community will help speed up any efforts to get this live!

**Comment by ht2** [comment]
Addressed in [v1.12.0](https://github.com/LearningLocker/learninglocker/releases/tag/v1.12.0)

**Comment by salexfo** [comment]
Hi,
We have upgraded to v1.12.1 and it still doesn't help.
See the image attached.
![selection_616](https://cloud.githubusercontent.com/assets/8767588/14351241/d594d730-fcd6-11e5-8439-4eebf94a30f9.png)

**Comment by ht2** [comment]
The aggregation query that drives this query simply takes that long to process. Moving forward we are looking at ways to place daily counts into cached buckets, but for the moment this is simply a limitation of querying this amount of data into the format required for that graph to render. You may want to look at writing your own [aggregation queries](https://docs.mongodb.org/manual/aggregation/) if you are reliant on these numbers. 

You will notice that the page is no longer reliant on that data loading however, so even though it takes 17s on your instance to load, it does not block the UI anymore (as it has been moved to be an XHR request).

As always, contributions to the platform to help speed up and optimise issues like this are [always appreciated](http://docs.learninglocker.net/contribute/).

**Comment by ht2** [comment]
Also, with this level of usage you may also want to consider our Enterprise version, which is more appropriate for these kind of numbers. https://learninglocker.net/enterprise/

**Comment by salexfo** [comment]
@ht2 thanks for the quick response.

The page itself takes around 20 seconds to show the UI - is it because the collection size? If that's the case - can we do anything about it?

**Comment by ht2** [comment]
Hmm, it shouldn't take that long to load the page now that the graph data is extracted into its own request. At the top of this issue you mentioned that you had made some changes originally to the source code - have you fully reverted to the repo's version now?

The collection is quite large but not unmanageable. What version of Mongo are you using and what storage engine? You should also read my blog entry here: https://learninglocker.net/blog/learning-locker-v1-12/

**Comment by salexfo** [comment]
Mongo 3.3, wiredTIger. All changes were reverted.

**Comment by ht2** [comment]
OK, in which case look into the indexing in my blog. You could use [Mongo Profiling](https://docs.mongodb.org/manual/tutorial/manage-the-database-profiler/) to start to see where bottlenecks are  but I would expect the page itself to load instantly as the only database query of real complication on that page is the count, which should be using our forked version of the jenseggers library to ensure it uses the PHP driver's native method.

**Comment by salexfo** [comment]
@ht2. We have already utilized indexing and profiling. I guess that's just a big data set.

**Comment by ht2** [comment]
We have similar with load times in the region of 200ms for that page (not including the aggregation query for the graph). Something else must be up

**Comment by salexfo** [comment]
@ht2. OK, we will try to investigate further. Thanks for your help

**Comment by ht2** [comment]
You should run profiling on the queries used to load that page and see where bottlenecks are occurring. There are many things to think about on the Mongo side including the storage medium used (e.g. PCIe flash vs SSD vs HDD) and RAM size. Is this a sharded/replica set configuration? If sharded have you used the best shard key for the collection? I suspect that the issues lie at the data end of the issue - but it might be worth stepping through the PHP used to load that page to see where issues might lie. The latest version of LL includes the Clockwork debugging component (https://github.com/itsgoingd/clockwork) which can help massively in measuring timings and seeing what is happening when. 

Let us know how you progress and don't hesitate to get in contact with us directly at HT2 if you want talk about how we can help you with the above questions

**Comment by salexfo** [comment]
@ht2 - I've installed the clockwork chrome extension, but don't get any data after I've selected an LRS and then click on "statements" due to the fact that the connection breaks with 504 error (attached)
![selection_626](https://cloud.githubusercontent.com/assets/8767588/15508368/d5a53d20-21d7-11e6-89ca-d12229720e97.png)

**Comment by salexfo** [comment]
I've manually deleted some statements and now I have an output (attached). Do you think compund indexes might do the trick?

![selection_627](https://cloud.githubusercontent.com/assets/8767588/15510125/dd542d7c-21de-11e6-9f1f-acb1cdb487ad.png)

**Comment by ht2** [comment]
It absolutely will, see my aforemetioned blog entry here: https://learninglocker.net/blog/learning-locker-v1-12/

If you want, try pulling from develop and running a migration. I have added all those suggested indexes to a new migration here: https://github.com/LearningLocker/learninglocker/commit/6529180728a1349444d2db2bf464d40cad8a2dde

**Comment by salexfo** [comment]
@ht2 Awesome! works great now!
